version: "3"

services:
    hive_game:
        build:
            context: ./app
        ports:
            - "8080:80"
        depends_on:
            - hive_db
        command: php -S 0.0.0.0:80
    hive_db:
        build:
            context: ./db
        ports:
            - "3307:3306"
    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8081:8080"
        networks:
            - hive_network
        depends_on:
            - hive_game
            - hive_db
            - sonarqube
    sonarqube:
        image: sonarqube
        ports:
            - "9000:9000"
        networks:
            - hive_network
        depends_on:
            - hive_game
            - hive_db

networks:
    hive_network:
      name: hive_network
