version: "3"

services:
    hive_game:
        build:
            context: ./app
        ports:
            - "8080:80"
        depends_on:
            - hive_db
        command: php -S 0.0.0.0:80
    hive_db:
        build:
            context: ./db
        ports:
            - "3307:3306"